# Dockerfile.blockchain

# Use a Python base image
FROM python:3.8.9

# Set working directory
WORKDIR /app

# Copy requirements and entrypoint script into the container
ADD ./blockchain/requirements.txt .
ADD ./blockchain/entrypoint.sh .

# Install dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Ensure entrypoint.sh is executable
RUN chmod +x /app/entrypoint.sh

# Expose the port Django will run on
EXPOSE $BLOCKCHAIN_PORT

# Run the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]
